/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ShippingList */

#ifndef _Included_c_lib_ShippingjList
#define _Included_c_lib_ShippingjList
/*
 * Class:     c_lib_ShippingjList
 * Method:    ShippingList
 * Signature: (Ljava/lang/String;)V
 */
    JNIEXPORT jdouble JNICALL Java_c_1lib_ShippingjList_ShippingList
  (JNIEnv *, jclass, jintArray);

#endif
